CREATE TABLE users(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(255) UNIQUE NOT NULL,
    email varchar(255) UNIQUE NOT NULL,
    password varchar(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE projects (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    project_name varchar NOT NULL,
    is_active boolean DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE tasks (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id bigint NOT NULL,
    task_name varchar NOT NULL,
    priority int DEFAULT 1,
    created_at TIMESTAMP NOT NULL,
    deadline TIMESTAMP NOT NULL,
    task_status varchar(11) NOT NULL,

    CONSTRAINT fk_project_id FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    task_id bigint NOT NULL,
    comment text NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_task_id FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);

CREATE TABLE developers(
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,

    CONSTRAINT fk_project_id FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
